<? if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die(); ?>
<?
$aMenuLinks = array(
    array(
        "Вопрос-ответ",
        "/#faq",
        array(),
        array(),
        ""
    ),
    array(
        "Интерьеры",
        "/#interiors",
        array(),
        array(),
        ""
    ),
    array(
        "Блог",
        "/news/",
        array(),
        array(),
        ""
    ),
    array(
        "",
        "",
        array(),
        array(),
        ""
    ),
    array(
        "Вакансии",
        "/vacancy/",
        array(),
        array(),
        ""
    ),
    array(
        "Посчитать доход",
        "/#calculator",
        array(),
        array(),
        ""
    )
);
?>